services:
  - docker
os: linux
language: minimal
stages:
  - lint
  - test
  - name: push-image-tag
    if: type != pull_request
  - name: push-image-latest
    if: type != pull_request

jobs:
  include:
    - stage: lint
      language: node_js
      node_js: '12'
      script:
        - npm ci
        - npm run lint
    - stage: test
      script:
      - ./runTestsAll.sh
    - stage: push-image-tag
      if: (tag =~ /^[0-9]+\.[0-9]+\.[0-9]+(\-(alpha|beta|rc)\.[0-9]+)?$/)
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_IMAGE:$TRAVIS_TAG .
      - docker push $DOCKER_IMAGE:$TRAVIS_TAG
      - |
        if [ -n "$MICROBADGE_TOKEN" ]; then
          curl -XPOST https://hooks.microbadger.com/images/theoapp/theo/${MICROBADGE_TOKEN}
        fi

    - stage: push-image-latest
      if: (tag =~ /^[0-9]+\.[0-9]+\.[0-9]+$/)
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker pull $DOCKER_IMAGE:$TRAVIS_TAG
      - docker tag $DOCKER_IMAGE:$TRAVIS_TAG $DOCKER_IMAGE:latest
      - docker push $DOCKER_IMAGE:latest
      - |
        if [ -n "$THEO_UPDATE_TOKEN" ]; then
          curl -H "Content-Type: application/json" -H "Authorization: Bearer $THEO_UPDATE_TOKEN" \
            -d '{"code": "'$TRAVIS_TAG'", "latest": true }' https://update.theo.authkeys.io/version
        fi
      - |
        if [ -n "$MICROBADGE_TOKEN" ]; then
          curl -XPOST https://hooks.microbadger.com/images/theoapp/theo/${MICROBADGE_TOKEN}
        fi
